language: java
jdk:
- oraclejdk8

cache:
  directories:
  - "~/.m2"

before_install:
  - export REPO=`git config remote.origin.url`
  - echo $REPO
  - git clone $REPO public
  - cd public
  - ls -lA
  - pwd
  - cd $RELEASE_COMPONENT
  - pwd
  - ls -lA

before_deploy:
  - echo "Begining deployment of ${RELEASE_COMPONENT}"
  - pwd
  - ls -lA
  - mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]'
  - export component_version=$(mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]')

deploy:
  - provider: releases
    api_key:
      secure: Uro4YN687ZIFaJTSPhiAo8s9aWH+UrS2zMn1WHlrtNobReaD7LgSk5nyBjaYhiDEX6fokfOaVaQM9W5vmrNmmMxBkdDnHTEI9DlSvbnc2sZfhf0sGAvLZcRVx5fipFxCakAQcK47BDNJC+CZ5s6Zgq7kv7WZA2f7Cf1rSPBFtDo9FQ2inOVfidxG+55o8hZvoAo8jb8om/8QoXqmKxcmK1m7sQbGGnNSoIbp1+iU53hqhHY8TXMeG0Tw7e/DrvqeaNnBj8s/tcTFzg9MHqiRySKDS12FJDaSVbNNirw14X+7/ZK0GdZUHOhjnH+1YIJTI83Ia9LksJBKz0BIROUneshJqUo/V/IajN2Ee88vl4ZpsozHBxLilz4GjoIpTZPegJIy0rOtG7Thvfaj26WqQSsa7z+0PY5ol2E+NItTVJCGddQKs/+srAKSssiyuo6O5e8MYDskpB/gvTKm1dWIUWXPu8sEYka/jpoDGsQy6FcHHKQolj4ZJOoeaEye6MKxJ9QaR0o0rGfxnGklmitvsQq84eJvsmY4Tm5vnOtLg/7irb80QZZgXihP6iqbr1zrR62Flgv2qoh4gyXN7Al9X8CUk7wvyXk9A40vUEXLXKBmAOGbF4VMp/Ywa3vj7vfFhqzUw3cmT8XAXoMpF8Yns05lMjEQsord9cS9YDBwa0g=

    file_glob: true
    file: '**/target/xdl-${component_version}-dist.zip'
    skip_cleanup: true
    on:
      repo: kusid/test-travis-releases
      branch: master
      condition: $RELEASE_COMPONENT = xdl
    name: XDL_${component_version}

  - provider: releases
    api_key:
      secure: Uro4YN687ZIFaJTSPhiAo8s9aWH+UrS2zMn1WHlrtNobReaD7LgSk5nyBjaYhiDEX6fokfOaVaQM9W5vmrNmmMxBkdDnHTEI9DlSvbnc2sZfhf0sGAvLZcRVx5fipFxCakAQcK47BDNJC+CZ5s6Zgq7kv7WZA2f7Cf1rSPBFtDo9FQ2inOVfidxG+55o8hZvoAo8jb8om/8QoXqmKxcmK1m7sQbGGnNSoIbp1+iU53hqhHY8TXMeG0Tw7e/DrvqeaNnBj8s/tcTFzg9MHqiRySKDS12FJDaSVbNNirw14X+7/ZK0GdZUHOhjnH+1YIJTI83Ia9LksJBKz0BIROUneshJqUo/V/IajN2Ee88vl4ZpsozHBxLilz4GjoIpTZPegJIy0rOtG7Thvfaj26WqQSsa7z+0PY5ol2E+NItTVJCGddQKs/+srAKSssiyuo6O5e8MYDskpB/gvTKm1dWIUWXPu8sEYka/jpoDGsQy6FcHHKQolj4ZJOoeaEye6MKxJ9QaR0o0rGfxnGklmitvsQq84eJvsmY4Tm5vnOtLg/7irb80QZZgXihP6iqbr1zrR62Flgv2qoh4gyXN7Al9X8CUk7wvyXk9A40vUEXLXKBmAOGbF4VMp/Ywa3vj7vfFhqzUw3cmT8XAXoMpF8Yns05lMjEQsord9cS9YDBwa0g=

    file_glob: true
    file: '**/target/xql-${component_version}-dist.zip'
    skip_cleanup: true
    on:
      repo: kusid/test-travis-releases
      branch: master
      condition: $RELEASE_COMPONENT = xql
    name: XQL_${component_version}

  - provider: releases
    api_key:
      secure: Uro4YN687ZIFaJTSPhiAo8s9aWH+UrS2zMn1WHlrtNobReaD7LgSk5nyBjaYhiDEX6fokfOaVaQM9W5vmrNmmMxBkdDnHTEI9DlSvbnc2sZfhf0sGAvLZcRVx5fipFxCakAQcK47BDNJC+CZ5s6Zgq7kv7WZA2f7Cf1rSPBFtDo9FQ2inOVfidxG+55o8hZvoAo8jb8om/8QoXqmKxcmK1m7sQbGGnNSoIbp1+iU53hqhHY8TXMeG0Tw7e/DrvqeaNnBj8s/tcTFzg9MHqiRySKDS12FJDaSVbNNirw14X+7/ZK0GdZUHOhjnH+1YIJTI83Ia9LksJBKz0BIROUneshJqUo/V/IajN2Ee88vl4ZpsozHBxLilz4GjoIpTZPegJIy0rOtG7Thvfaj26WqQSsa7z+0PY5ol2E+NItTVJCGddQKs/+srAKSssiyuo6O5e8MYDskpB/gvTKm1dWIUWXPu8sEYka/jpoDGsQy6FcHHKQolj4ZJOoeaEye6MKxJ9QaR0o0rGfxnGklmitvsQq84eJvsmY4Tm5vnOtLg/7irb80QZZgXihP6iqbr1zrR62Flgv2qoh4gyXN7Al9X8CUk7wvyXk9A40vUEXLXKBmAOGbF4VMp/Ywa3vj7vfFhqzUw3cmT8XAXoMpF8Yns05lMjEQsord9cS9YDBwa0g=

    file_glob: true
    file:
      - "**/target/xloader-${component_version}-dist.zip"
      - "**/target/xstorOperations-${component_version}-dist.zip"
    skip_cleanup: true
    on:
      repo: kusid/test-travis-releases
      branch: master
      condition: $RELEASE_COMPONENT = xstore
    name: XSTORE_${component_version}