language: java
jdk:
  - oraclejdk8

# skip tests during the script phase
script:
  - cd $TRAVIS_BUILD_DIR/$RELEASE_COMPONENT
  - pwd
  - mvn clean install -U -e -DskipTests=true
  - mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]'
  - export component_version=$(mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]')
  - echo "component version is ${component_version}"

branches:
  only:
    - master

# echo git tags
after_script:
  - git tag

# pre-deploy steps
before_deploy:
  - echo "Beginning deployment of ${RELEASE_COMPONENT}"
  - pwd
  - ls -lA
  - export GIT_TAG="${RELEASE_COMPONENT}-v${component_version}"
  - git tag $GIT_TAG -a -m "Tagging from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://${GH_TOKEN}@github.com/kusid/test-travis-releases.git --tags

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
      branch: master
    target-branch: gh-pages
    keep-history: true


