language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - "~/.m2"

before_install:
  - export REPO=`git config remote.origin.url`
  - echo $REPO
  - git clone $REPO public
  - cd public
  - ls -lA
  - cd $RELEASE_COMPONENT
  - echo $RELEASE_COMPONENT
  - pwd
  - ls -lA

# skip install phase
install: true

# skip tests during the install phase
script:
  - mvn clean install -U -e -DskipTests=true

# echo location
after_script:
  - ls -lA

# tag before releasing to github
before_deploy:
  - echo "Beginning deployment of ${RELEASE_COMPONENT}"
  - pwd
  - ls -lA
  - mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]'
  - export component_version=$(mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]')
  - if [ -n "${RELEASE_COMPONENT}" ]; then git tag "${RELEASE_COMPONENT}-v${component_version}"; fi

deploy:
  - provider: releases
    api_key:
      secure: GT2+1ULIbQaeqeCy1JVYr0cCTcRnKyrWTGaouJKVbjibJ6BR4Q+OmNc6kTG2w76axmLFwcIj+pPhLUKKh8p8Wxn9/leTZBaXcfkXTcR6Fm6Cg+uMLHffKtaUC0bN9EbfH0THkC+MNwWkxFlagsxYgcKpfDT4LL4u1lLOhuT94HUk5o3Hn88vQ+aNiiAzyc0MrinMP8HUgwY3702gUM4/b8KJMbctmFM9XOaGosYWE8Eklzvv6yYVHYHwcjIjKa1T81SYfJ1i+oxfdJyc6EznYFa52FLdVVH+kpjXgnfvdnjv3lT7kty94Oi7YV9VF3xhDVwNK2E5rOkJ0ptVLZyFGTbVIDGkN7ppVLx5Lux1GeqoG/ye39/I/HBd/VmQxCz+37dPRp/Ge7at03m68IAV1ShwxHchOcIeTqRN0/kRme87fuyKwTgFlHHaMsn1Kltpg+UptH8QKpKv08iaR2T/JrvmbHPOgbTjnHYdDST1wUUrgUqgQlLaMDVvQmjtjqBHGvFLjJg9pdgTk5mbzxaRxVLD+DJLUauV53aqNFzIFmVfXhxAZilmmNla+PCP3z5QU9rawAPSgJp2Wh0qGvzTI7gjeWnM+RheIB1G/paxebpRz79ZUtIN/I3OAkP9BkBZJDvc3FY9sRaQ/Q3kN4NXjT2ZNJ+flrjz3uqCJ0RmGZ8=
    file: '**/target/xdl-${component_version}-dist.zip'
    file_glob: true
    skip_cleanup: true
    on:
      repo: kusid/test-travis-releases
      tags: true
      condition: ${RELEASE_COMPONENT} = xdl
    name: ${RELEASE_COMPONENT}-${component_version}

  - provider: releases
    api_key:
      secure: GT2+1ULIbQaeqeCy1JVYr0cCTcRnKyrWTGaouJKVbjibJ6BR4Q+OmNc6kTG2w76axmLFwcIj+pPhLUKKh8p8Wxn9/leTZBaXcfkXTcR6Fm6Cg+uMLHffKtaUC0bN9EbfH0THkC+MNwWkxFlagsxYgcKpfDT4LL4u1lLOhuT94HUk5o3Hn88vQ+aNiiAzyc0MrinMP8HUgwY3702gUM4/b8KJMbctmFM9XOaGosYWE8Eklzvv6yYVHYHwcjIjKa1T81SYfJ1i+oxfdJyc6EznYFa52FLdVVH+kpjXgnfvdnjv3lT7kty94Oi7YV9VF3xhDVwNK2E5rOkJ0ptVLZyFGTbVIDGkN7ppVLx5Lux1GeqoG/ye39/I/HBd/VmQxCz+37dPRp/Ge7at03m68IAV1ShwxHchOcIeTqRN0/kRme87fuyKwTgFlHHaMsn1Kltpg+UptH8QKpKv08iaR2T/JrvmbHPOgbTjnHYdDST1wUUrgUqgQlLaMDVvQmjtjqBHGvFLjJg9pdgTk5mbzxaRxVLD+DJLUauV53aqNFzIFmVfXhxAZilmmNla+PCP3z5QU9rawAPSgJp2Wh0qGvzTI7gjeWnM+RheIB1G/paxebpRz79ZUtIN/I3OAkP9BkBZJDvc3FY9sRaQ/Q3kN4NXjT2ZNJ+flrjz3uqCJ0RmGZ8=
    file: '**/target/xql-${component_version}-dist.zip'
    file_glob: true
    skip_cleanup: true
    on:
      repo: kusid/test-travis-releases
      tags: true
      condition: ${RELEASE_COMPONENT} = xql
    name: ${RELEASE_COMPONENT}-${component_version}

  - provider: releases
    api_key:
      secure: GT2+1ULIbQaeqeCy1JVYr0cCTcRnKyrWTGaouJKVbjibJ6BR4Q+OmNc6kTG2w76axmLFwcIj+pPhLUKKh8p8Wxn9/leTZBaXcfkXTcR6Fm6Cg+uMLHffKtaUC0bN9EbfH0THkC+MNwWkxFlagsxYgcKpfDT4LL4u1lLOhuT94HUk5o3Hn88vQ+aNiiAzyc0MrinMP8HUgwY3702gUM4/b8KJMbctmFM9XOaGosYWE8Eklzvv6yYVHYHwcjIjKa1T81SYfJ1i+oxfdJyc6EznYFa52FLdVVH+kpjXgnfvdnjv3lT7kty94Oi7YV9VF3xhDVwNK2E5rOkJ0ptVLZyFGTbVIDGkN7ppVLx5Lux1GeqoG/ye39/I/HBd/VmQxCz+37dPRp/Ge7at03m68IAV1ShwxHchOcIeTqRN0/kRme87fuyKwTgFlHHaMsn1Kltpg+UptH8QKpKv08iaR2T/JrvmbHPOgbTjnHYdDST1wUUrgUqgQlLaMDVvQmjtjqBHGvFLjJg9pdgTk5mbzxaRxVLD+DJLUauV53aqNFzIFmVfXhxAZilmmNla+PCP3z5QU9rawAPSgJp2Wh0qGvzTI7gjeWnM+RheIB1G/paxebpRz79ZUtIN/I3OAkP9BkBZJDvc3FY9sRaQ/Q3kN4NXjT2ZNJ+flrjz3uqCJ0RmGZ8=
    file:
      - '**/target/xloader-${component_version}-dist.zip'
      - '**/target/xstorOperation-${component_version}-dist.zip'
    file_glob: true
    skip_cleanup: true
    on:
      repo: kusid/test-travis-releases
      tags: true
      condition: ${RELEASE_COMPONENT} = xstore
    name: ${RELEASE_COMPONENT}-${component_version}
